/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wangjie_com_newproject_application_NativeMethod */

#ifndef _Included_wangjie_com_newproject_application_NativeMethod
#define _Included_wangjie_com_newproject_application_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wangjie_com_newproject_application_NativeMethod
 * Method:    fuck
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wangjie_com_newproject_application_NativeMethod_fuck
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
